In [2]:
leven = []
lodd = []

[leven.append(item) if item%2==0 else lodd.append(item) for item in range(100)]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [3]:
leven, lodd

([0,
  2,
  4,
  6,
  8,
  10,
  12,
  14,
  16,
  18,
  20,
  22,
  24,
  26,
  28,
  30,
  32,
  34,
  36,
  38,
  40,
  42,
  44,
  46,
  48,
  50,
  52,
  54,
  56,
  58,
  60,
  62,
  64,
  66,
  68,
  70,
  72,
  74,
  76,
  78,
  80,
  82,
  84,
  86,
  88,
  90,
  92,
  94,
  96,
  98],
 [1,
  3,
  5,
  7,
  9,
  11,
  13,
  15,
  17,
  19,
  21,
  23,
  25,
  27,
  29,
  31,
  33,
  35,
  37,
  39,
  41,
  43,
  45,
  47,
  49,
  51,
  53,
  55,
  57,
  59,
  61,
  63,
  65,
  67,
  69,
  71,
  73,
  75,
  77,
  79,
  81,
  83,
  85,
  87,
  89,
  91,
  93,
  95,
  97,
  99])

In [7]:
la = [1,2,3]
lb = [4,5,6]
lc = []
lc = [(x,y) for x in la for y in lb ]
lc

[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]

In [10]:
t = (1,2,3)
t = t + t+t
t

(1, 2, 3, 1, 2, 3, 1, 2, 3)

In [11]:
l = [1,2,3]
l = l+l+l
l

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [13]:
t1 = (1,2,3)
t2 = (4,5,6)
t = t1+t2
t

(1, 2, 3, 4, 5, 6)

In [15]:
t = (t1,t2)
t


((1, 2, 3), (4, 5, 6))

In [17]:
l1 = ['Hong', 'Khanh']
t1 = ('aaa', 'bbb')
t = (l1,t1)
t

(['Hong', 'Khanh'], ('aaa', 'bbb'))

In [19]:
type(t[1])

tuple

In [20]:
t = l1 + t1

TypeError: can only concatenate list (not "tuple") to list

In [21]:
l = [1,2,3]
t = (4,5,6)
t1 = (1,2,3, t, l)
t1

(1, 2, 3, (4, 5, 6), [1, 2, 3])

In [22]:
t1[4][2] = 10
t1

(1, 2, 3, (4, 5, 6), [1, 2, 10])

In [24]:
t1[2] = 5


TypeError: 'tuple' object does not support item assignment

In [25]:
s = {5,6,8,1,4}
s

{1, 4, 5, 6, 8}

In [31]:
A = {1,2,3,4,5}
B = {7,6,5,4,3}
A - B


{1, 2}

In [29]:
A ^B

{1, 2, 6, 7}

In [30]:
A|B

{1, 2, 3, 4, 5, 6, 7}

In [32]:
A&B

{3, 4, 5}

In [34]:
dictionary = {"hs1":"Hong","hs2":"Tuan","hs3":"Teo"}
dictionary

{'hs1': 'Hong', 'hs2': 'Tuan', 'hs3': 'Teo'}

In [35]:
dictionary.keys()


dict_keys(['hs2', 'hs3', 'hs1'])

In [36]:
dictionary.values()

dict_values(['Tuan', 'Teo', 'Hong'])

In [51]:
dictionary["hs4"] = 'Khanh'

In [52]:
[print(item[1]) for item in dictionary.items()]


Khanh
Tuan
Teo
Hong


[None, None, None, None]

In [46]:
diem = dict(A=5, B=10, C = 8)
diem

{'A': 5, 'B': 10, 'C': 8}

In [49]:
result = {x:x**2 for x in range(100)}
result

{0: 0,
 1: 1,
 2: 4,
 3: 9,
 4: 16,
 5: 25,
 6: 36,
 7: 49,
 8: 64,
 9: 81,
 10: 100,
 11: 121,
 12: 144,
 13: 169,
 14: 196,
 15: 225,
 16: 256,
 17: 289,
 18: 324,
 19: 361,
 20: 400,
 21: 441,
 22: 484,
 23: 529,
 24: 576,
 25: 625,
 26: 676,
 27: 729,
 28: 784,
 29: 841,
 30: 900,
 31: 961,
 32: 1024,
 33: 1089,
 34: 1156,
 35: 1225,
 36: 1296,
 37: 1369,
 38: 1444,
 39: 1521,
 40: 1600,
 41: 1681,
 42: 1764,
 43: 1849,
 44: 1936,
 45: 2025,
 46: 2116,
 47: 2209,
 48: 2304,
 49: 2401,
 50: 2500,
 51: 2601,
 52: 2704,
 53: 2809,
 54: 2916,
 55: 3025,
 56: 3136,
 57: 3249,
 58: 3364,
 59: 3481,
 60: 3600,
 61: 3721,
 62: 3844,
 63: 3969,
 64: 4096,
 65: 4225,
 66: 4356,
 67: 4489,
 68: 4624,
 69: 4761,
 70: 4900,
 71: 5041,
 72: 5184,
 73: 5329,
 74: 5476,
 75: 5625,
 76: 5776,
 77: 5929,
 78: 6084,
 79: 6241,
 80: 6400,
 81: 6561,
 82: 6724,
 83: 6889,
 84: 7056,
 85: 7225,
 86: 7396,
 87: 7569,
 88: 7744,
 89: 7921,
 90: 8100,
 91: 8281,
 92: 8464,
 93: 8649,
 94: 8836,
 95: 9025,


In [62]:
def tong(n1,n2,n3=10):
    t = n1+n2+n3
    return t

In [64]:
tongn = tong(6,4)
print(tongn)
tongn

20


20

In [65]:
def tong(*data):
    t=0
    for item in data:
        t += item
    return t

In [68]:
ketqua = tong(10,20,30,40,80)
ketqua

180

In [80]:
def tong(*data): # * truyền nhiều tham số
    kq = []
    for item in data:
        t=0
        for n in item:
            t += n
        kq.append(t)
    return kq

In [82]:
tong([5,6,8],[8,9,4])

[19, 21]

In [85]:
def dienthoai(**data): # ** truyền nhiều tham số 2 giá trị
    count = 0
    for name,price in data.items():
        row = '{:10} {:10}'.format(name,price)
        print(row)
        count += price
    return count

In [87]:
tong = dienthoai(iphone=50000,ss=30000,nokia=5000)
print('-'*30)
print('{:10} {:10}'.format('Tong:', tong))

nokia            5000
iphone          50000
ss              30000
------------------------------
Tong:           85000


In [102]:
def tong(n1,n2,n3, *data, **data2):
    t1=t2=t3=0
    t1 = n1+n2+n3
    for item in data:
        t2 += item
    for k,v in data2.items():
        t3 += v
    t = [t1,t2,t3]
    return t

In [103]:
tong(10,20,50,11,12,13,14,15, one = 100, two=200, three=300)

[80, 65, 600]

Iterator

In [1]:
l = [1,2,3,4,5,6]
I = iter(l)

In [2]:
type(I)

list_iterator

In [5]:
I.__next__()

3

In [6]:
l = 'Nguyen Gia Hong'
I = iter(l)

In [7]:
type(I)

str_iterator

In [9]:
I.__next__()

'N'

Generator

In [11]:
x = range(0,10,2)
for i in x:
    print(i)

0
2
4
6
8


In [15]:
def myrange(start, end, step):
    i = start
    while(i<end):
        yield i #tạo biến hứng i, hàm sẽ trả ra giá trị như return nhưng chạy tiếp tục
        i += step

In [16]:
myrange(0,5,2)

<generator object myrange at 0x000002EE0720F410>

In [17]:
t = myrange(0,5,2)
for i in t:
    print(i)

0
2
4


Ex1

In [34]:
def countchar(*data):
    dic = {}
    for i in data:
        for c in i:
            c = c.lower()
            if c in dic:
                dic[c] += 1
            else:
                dic[c] = 1
    return dic

In [35]:
countchar('tuan', 'teo', 'Python')

{'a': 1, 'e': 1, 'h': 1, 'n': 2, 'o': 2, 'p': 1, 't': 3, 'u': 1, 'y': 1}

Ex2

In [44]:
def myrange(*param):
    start = end = step = 0
    if (len(param) == 3):
        start = param[0]
        end = param[1]
        step = param[2]
    elif (len(param) == 2):
        start = param[0]
        end = param[1]
        step = 1
    else:
        start = 0
        end = param[0]
        step = 1
    i = start
    while(i<end):
        yield i
        i += step

In [49]:
t = myrange(10)

In [50]:
for i in t:
    print(i)

0
1
2
3
4
5
6
7
8
9


OOP

In [ ]:
class Car:
    fuel = 'Xang'
    maxspeed = 150

In [52]:
polo = Car()

In [54]:
print(polo.fuel)

Xang


In [55]:
type(polo)

__main__.Car

In [56]:
class Car:
    fuel = 'Xang'
    maxspeed = 150
    
    def drive(self): #self, chính bản thân class
        print('Xe chay voi toc do:', self.maxspeed)

In [57]:
mini = Car()

In [58]:
mini.drive()

Xe chay voi toc do: 150


In [61]:
class Car:
    fuel = 'Xang'
    maxspeed = 150
    
    def drive(self, maxspeed): #self, chính bản thân class
        print('Xe chay voi toc do:',maxspeed)

In [62]:
hong = Car()
hong.drive(300)

Xe chay voi toc do: 300


In [63]:
nhan = Car()
nhan.drive(900)

Xe chay voi toc do: 900


Constructor

In [64]:
class Student:
    
    def info(self, name, age):
        print('Name: ', name, ' Age: ', age)

In [65]:
hong = Student()
hong.info('Hong', 26)

Name:  Hong  Age:  26


In [66]:
class Student:
    
    def __init__(self, name, age): #Constructor, ko cần phải gọi mothods
        print('Name: ', name, ' Age: ', age)

In [68]:
Teo = Student('Teo', 25)

Name:  Teo  Age:  25


In [69]:
class Student:
    
    def __init__(self, name, age): #Constructor, ko cần phải gọi methods (Trong init, ko được phép dùng return)
        print('Name: ', name, ' Age: ', age)
    def __str__(self):
        return('-------------------------')

In [72]:
hong = Student('Hong', 26)
print (hong)

Name:  Hong  Age:  26
-------------------------


In [73]:
class Student:
    
    def __init__(self, name, age): #Constructor, ko cần phải gọi methods (Trong init, ko được phép dùng return)
        print('Name: ', name, ' Age: ', age)
    def __str__(self):
        return('-------------------------')
    def __del__(self):
        print('destroyed')

In [74]:
hong = Student('Hong', 26)

Name:  Hong  Age:  26


In [75]:
print(hong)

-------------------------


In [76]:
del hong

destroyed


In [77]:
print(hong)

NameError: name 'hong' is not defined

inheritance

In [85]:
class Person:
    
    def name(self, ten):
        print('Toi ten la: ', ten)

In [86]:
hong = Person()
hong.name('nguyen gia hong')

Toi ten la:  nguyen gia hong


In [87]:
class Student:
    
    def age(self, age):
        print('Tuoi la: ', age)

In [88]:
teo = Student()
teo.age(26)

Tuoi la:  26


In [89]:
class Student (Person): #kế thừa class Person
    
    def age(self, age):
        print('Tuoi la: ', age)

In [90]:
nhan = Student()
nhan.name('Nguyen thanh nhan')
nhan.age(25)

Toi ten la:  Nguyen thanh nhan
Tuoi la:  25


In [99]:
class Person:
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def info(self):
        print('Toi ten la: ', self.name, ' Tuoi cua toi la: ', self.age)

In [101]:
hong = Person('Nguyen Gia Hong', 26)
hong.info()

Toi ten la:  Nguyen Gia Hong  Tuoi cua toi la:  26


In [104]:
class Person:
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def info(self):
        print('Toi ten la: ', self.name, ' Tuoi cua toi la: ', self.age)

class Student (Person):
    
    def __init__(self, name, age, grade):
        Person.__init__(self,name,age)
        self.grade = grade
    
    def infograde(self):
        print('Lop cua ban la: ', self.grade)

In [106]:
hong = Student('Nguyen Gia Hong', 25, '9/8')
hong.info()
hong.infograde()

Toi ten la:  Nguyen Gia Hong  Tuoi cua toi la:  25
Lop cua ban la:  9/8


Read File

In [2]:
fp = open('data/list.txt', 'r')
for line in fp:
    print(line, end='')
fp.close()

Python here
Python here

write/read

In [3]:
fp = open('data/write.txt', 'w')
fp.write('Hong')
fp.write('\n')
fp.write('Nguyen')
fp.write('\n')
fp.close()

In [5]:
rFile = open('data/list.txt', 'r')
wFile = open('data/write.txt', 'w')

for line in rFile:
    print(line, file=wFile, end='')
print('Done')

Done


Buffer

In [7]:
BUFFERSIZE = 25000 #ghi mỗi lần 25000 byte
rFile = open('data/list.txt', 'r')
wFile = open('data/write.txt', 'w')

buffer = rFile.read(BUFFERSIZE)

i = 0
while(len(buffer)):
    i += 1
    wFile.write(buffer)
    print(i, '{} byte'.format(len(buffer)))
    buffer = rFile.read(BUFFERSIZE)
print('Done')

1 23 byte
Done



Method-File

In [10]:
f = open('data/list.txt', 'r')

fpos = f.tell() # đọc đến vị trí nào
print('Doc toi vi tri', fpos)

f.seek(0) # đưa đến phần muốn đọc
print('-' * 50)

data = f.read()
print(len(data))
print(data)

Doc toi vi tri 0
--------------------------------------------------
23
Python here
Python here


Standard Module

In [11]:
import random

In [15]:
x = list(range(50))
x

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [17]:
random.shuffle(x)
print(x)

[30, 34, 28, 3, 40, 19, 1, 5, 14, 23, 37, 43, 20, 35, 29, 4, 47, 8, 10, 41, 32, 7, 48, 25, 27, 38, 6, 13, 24, 18, 17, 42, 12, 31, 46, 2, 11, 16, 39, 9, 0, 33, 44, 21, 49, 15, 22, 36, 45, 26]


In [21]:
import datetime as dt

In [27]:
date = dt.datetime.today()
print(date)

2018-03-07 19:33:35.578305


In [31]:
t =dt.datetime.now()
print(t.hour)

19


In [32]:
import os as o

In [33]:
o.getcwd()

'C:\\Users\\StrikeWade\\Desktop\\Python'

In [40]:
path = o.getenv('PATH')
print(path)

C:\Users\StrikeWade\Anaconda3\Library\bin;C:\Users\StrikeWade\Anaconda3\Library\bin;C:\Users\StrikeWade\Anaconda3\Scripts;C:\Users\StrikeWade\Anaconda3\Library\bin;C:\Users\StrikeWade\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\StrikeWade\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\cuda\bin;C:\Program Files\cuda\lib\x64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\protoc\bin;C:\Program Files\opencv\build\x64\vc14\bin;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA GPU Computi

Exception-Handling

In [42]:
try:
    a = 100
    b = 0
    x = a/b
except:
    print('b not zero')

b not zero


In [43]:
try:
    a = 100
    b = 0
    x = a/b
except ZeroDivisionError as error:
    print('Error: ', error)

Error:  division by zero


Multi Exception

In [50]:
a = 100
b = 10

x = (a*b)+(1000*a)/(a/b)
print('x =',x)

f = open('teo.txt', 'r')
for line in f:
    print(line)

x = 11000.0


FileNotFoundError: [Errno 2] No such file or directory: 'teo.txt'

In [53]:
try:
    a = 100
    b = 20

    x = (a*b)+(1000*a)/(a/b)
    print('x =',x)

    f = open('teo.txt', 'r')
    
    for line in f:
        print(line)
        
except ZeroDivisionError as error:
    print('Lỗi', error)
except FileNotFoundError as error:
    print('Lỗi', error)

Lỗi division by zero


import sqlite

In [57]:
import sqlite3
db = sqlite3.connect('data/school.db')
db.execute('Drop table if exists student')
db.execute('Create table student (id integer primary key  autoincrement  not null, name varchar)')

In [60]:
db.execute("insert into student(name) values ('Nguyen Thanh Nhan')")
db.execute("insert into student(name) values ('Tran Thuong Khanh')")
db.execute("insert into student(name) values ('Nguyen Hoang')")
db.execute("insert into student(name) values ('Tran Chi Lan')")

In [61]:
db.commit()

In [71]:
results = db.execute('select * from student')
results

In [72]:
for row in results:
    print(row) 

(1, 'Nguyen Gia Hong')
(2, 'Nguyen Thanh Nhan')
(4, 'Nguyen Hoang')
(5, 'Tran Chi Lan')


In [65]:
print('-----' * 10)

--------------------------------------------------


In [69]:
results = db.execute("select * from student where name = 'Tran Khanh'")
for row in results:
    print(row)

(3, 'Tran Khanh')


In [67]:
db.execute("update student set name = 'Tran Khanh' where id = 3")

In [70]:
db.execute("delete from student where id = 3")

In [73]:
db.commit()

Arrays

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]

In [4]:
a1 = np.array(a)
a1

array([1, 2, 3, 4])

In [7]:
b = [4,5,6,7]
c = [8,9,10,11]
b1 = np.array(b)
c1 = np.array(c)

In [8]:
a1,b1,c1

(array([1, 2, 3, 4]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]))

In [10]:
sumarr = np.array([a1,b1,c1])
sumarr

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
sumarr.shape

(3, 4)

In [14]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
B = range(10)
B

range(0, 10)

In [21]:
C = np.arange(50)
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [22]:
C.shape

(50,)

In [27]:
C.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [29]:
D = np.arange(100).reshape(10,10)
D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
D.shape

(10, 10)

In [32]:
zero_D = np.zeros_like(D)
zero_D

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

Array Arithmetic

In [33]:
arr = np.array([ [1,2,3,4],[5,6,7,8] ])

In [34]:
arr+ 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [35]:
arr**arr

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]], dtype=int32)

In [38]:
#Transpose
arr_T = np.transpose(arr) # or arr.T
arr_T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [39]:
arr.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Array Slice

In [41]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
a1 = A[:10]
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a1[:] = 100
a1
A

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [48]:
A

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [50]:
B = A
B

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [52]:
A = np.arange(30).reshape(5,6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [53]:
A[2]

array([12, 13, 14, 15, 16, 17])

In [54]:
A[2][5]

17

In [59]:
A[:2]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [60]:
A[:2, 1:3]

array([[1, 2],
       [7, 8]])

In [61]:
A[[0,2,4]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [63]:
x = np.random.randint(1,10)
x

4

In [76]:
x = []
y = []
for i in range(10):
    x.append(np.random.randint(1,10))
    y.append(np.random.randint(1,10))

In [77]:
x,y

([9, 9, 7, 1, 8, 5, 2, 8, 8, 1], [2, 4, 8, 4, 2, 9, 4, 6, 9, 7])

In [78]:
type(x)

list

In [79]:
x = np.array(x)
y = np.array(y)

In [80]:
type(x)

numpy.ndarray

In [81]:
x,y

(array([9, 9, 7, 1, 8, 5, 2, 8, 8, 1]), array([2, 4, 8, 4, 2, 9, 4, 6, 9, 7]))

In [82]:
np.add(x,y)

array([11, 13, 15,  5, 10, 14,  6, 14, 17,  8])

In [85]:
np.maximum(x,y)

array([9, 9, 8, 4, 8, 9, 4, 8, 9, 7])

In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,10)
x

4

In [13]:
x = []
y = []
for i in range(10):
    x.append(np.random.randint(1,10))
    y.append(np.random.randint(1,10))

In [14]:
x = np.array(x)
y = np.array(y)

In [6]:
x,y

(array([6, 2, 7, 9, 7, 8, 6, 1, 8, 1]), array([3, 5, 3, 5, 2, 7, 7, 1, 9, 2]))

In [7]:
x.sort()

In [8]:
x

array([1, 1, 2, 6, 6, 7, 7, 8, 8, 9])

In [9]:
x

array([1, 1, 2, 6, 6, 7, 7, 8, 8, 9])

In [12]:
np.unique(x)
np.unique(y)

array([1, 2, 3, 5, 7, 9])

In [18]:
b = np.greater(x,y)
b

array([ True, False,  True, False,  True, False, False, False,  True,
       False])

In [19]:
b.all()

False

In [20]:
b.any()

True

In [21]:
np.equal(x,y)

array([False, False, False, False, False, False, False,  True, False,
       False])

Pandas

In [23]:
import numpy as np
from numpy.random import randn
import pandas as pd
from pandas import Series, DataFrame

In [25]:
s1 = Series([10,20,30,40])
s1

0    10
1    20
2    30
3    40
dtype: int64

In [26]:
s2 = Series([10,20,30,40], index=['A','B','C','D'])
s2

A    10
B    20
C    30
D    40
dtype: int64

In [30]:
diem = [10,9,10,7]
hocsinh = ['Teo','Tuan','Hong','Khanh']

In [32]:
s3 = Series(diem, index=hocsinh)
s3

Teo      10
Tuan      9
Hong     10
Khanh     7
dtype: int64

In [34]:
s3['Teo']

10

In [37]:
'Hong' in s3

True

In [38]:
type(s3)

pandas.core.series.Series

In [40]:
s3d = s3.to_dict()
type(s3d)

dict

In [41]:
s3d

{'Hong': 10, 'Khanh': 7, 'Teo': 10, 'Tuan': 9}

In [42]:
s3

Teo      10
Tuan      9
Hong     10
Khanh     7
dtype: int64

In [43]:
pd.isnull(s3)

Teo      False
Tuan     False
Hong     False
Khanh    False
dtype: bool

In [44]:
pd.isnull(s3d)

False

In [45]:
pd.notnull(s3)

Teo      True
Tuan     True
Hong     True
Khanh    True
dtype: bool

In [49]:
s3.name = 'Danh sach'

In [50]:
s3

Teo      10
Tuan      9
Hong     10
Khanh     7
Name: Danh sach, dtype: int64

Index - ReIndex

In [52]:
import numpy as np
from numpy.random import randn
import pandas as pd
from pandas import Series, DataFrame

diem = [10,9,10,7]
hocsinh = ['Teo','Tuan','Hong','Khanh']
s3 = Series(diem, index=hocsinh)
s3

Teo      10
Tuan      9
Hong     10
Khanh     7
dtype: int64

In [53]:
s3.index

Index(['Teo', 'Tuan', 'Hong', 'Khanh'], dtype='object')

In [54]:
s3.values

array([10,  9, 10,  7], dtype=int64)

In [58]:
s3[2:]

Hong     10
Khanh     7
dtype: int64

In [64]:
x = list(range(11,16))
ind = ['A','B','C','D','E']

In [65]:
s4 = Series(x, index = ind)
s4

A    11
B    12
C    13
D    14
E    15
dtype: int64

In [69]:
ind2 = ['A','B','C','D','E','F','G']
s5 = s4.reindex(ind2, fill_value = 0)
s5

A    11
B    12
C    13
D    14
E    15
F     0
G     0
dtype: int64

Selection

In [73]:
import numpy as np
from numpy.random import randn
import pandas as pd
from pandas import Series, DataFrame

diem = [10,9,10,7]
hocsinh = ['Teo','Tuan','Hong','Khanh']
s3 = Series(diem, index=hocsinh)
s3

Teo      10
Tuan      9
Hong     10
Khanh     7
dtype: int64

In [74]:
s4 = s3 *2
s4

Teo      20
Tuan     18
Hong     20
Khanh    14
dtype: int64

In [76]:
s4[['Teo','Tuan']]

Teo     20
Tuan    18
dtype: int64

In [77]:
s4 < 20

Teo      False
Tuan      True
Hong     False
Khanh     True
dtype: bool

In [78]:
s4[s4<20]

Tuan     18
Khanh    14
dtype: int64

In [80]:
s4[s4==20]

Teo     20
Hong    20
dtype: int64

Data Alignment Sort

In [81]:
import numpy as np
from numpy.random import randn
import pandas as pd
from pandas import Series, DataFrame

diem = [10,9,10,7]
hocsinh = ['Teo','Tuan','Hong','Khanh']
s3 = Series(diem, index=hocsinh)
s3

Teo      10
Tuan      9
Hong     10
Khanh     7
dtype: int64

In [83]:
s8 = Series([0,1,2], index=['A','B','C'])
s9 = Series([3,4,5,6], index=['A','B','C','D'])
s8

A    0
B    1
C    2
dtype: int64

In [84]:
s9

A    3
B    4
C    5
D    6
dtype: int64

In [85]:
s8 + s9

A    3.0
B    5.0
C    7.0
D    NaN
dtype: float64

In [94]:
ind = 'a b c d e f g h i j'.split()
ind

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [95]:
type(ind)

list

In [96]:
x = []
for i in range(10):
    x.append(np.random.randint(1,100))

In [97]:
x

[61, 21, 78, 21, 55, 7, 86, 60, 28, 78]

In [98]:
s10 = Series(x, index=ind)
s10

a    61
b    21
c    78
d    21
e    55
f     7
g    86
h    60
i    28
j    78
dtype: int64

DataFrame

In [14]:
import numpy as np
from numpy.random import randn
import pandas as pd
from pandas import Series, DataFrame

In [15]:
diem = [10,8,9,5,6,7,9,4,10,5]
sinhvien = ['Hong','Khanh','Nhan','Lan','Hoang','Tri','Duc','Duong','Truong','Trong']

In [16]:
data = {'sinhvien': sinhvien, 'diem': diem}

In [17]:
data

{'diem': [10, 8, 9, 5, 6, 7, 9, 4, 10, 5],
 'sinhvien': ['Hong',
  'Khanh',
  'Nhan',
  'Lan',
  'Hoang',
  'Tri',
  'Duc',
  'Duong',
  'Truong',
  'Trong']}

In [18]:
df1 = DataFrame(data)
df1

diem sinhvien
0    10     Hong
1     8    Khanh
2     9     Nhan
3     5      Lan
4     6    Hoang
5     7      Tri
6     9      Duc
7     4    Duong
8    10   Truong
9     5    Trong

In [52]:
idx = 'A B C D E F'.split()
cols = 'col1 col2 col3 col4 col5 col6'.split()
x = []
for i in range(36):
    x.append(np.random.randint(1,100))
x = np.array(x)
x = x.reshape(6,6)
x

array([[86, 65, 63, 55,  5, 15],
       [82, 16, 44, 16, 86, 19],
       [13,  7, 56, 49, 79, 43],
       [83, 51, 58, 58, 60, 32],
       [93,  9, 27, 82, 18, 51],
       [93, 67, 72, 55, 62, 86]])

In [60]:
df2 = DataFrame(x, index=idx, columns=cols)
df2

col1  col2  col3  col4  col5  col6
A    86    65    63    55     5    15
B    82    16    44    16    86    19
C    13     7    56    49    79    43
D    83    51    58    58    60    32
E    93     9    27    82    18    51
F    93    67    72    55    62    86

In [61]:
new_idx = 'A B C D E F G H K'.split()

In [67]:
df3 = df2.reindex(index=new_idx, fill_value=0)
df3

col1  col2  col3  col4  col5  col6
A    86    65    63    55     5    15
B    82    16    44    16    86    19
C    13     7    56    49    79    43
D    83    51    58    58    60    32
E    93     9    27    82    18    51
F    93    67    72    55    62    86
G     0     0     0     0     0     0
H     0     0     0     0     0     0
K     0     0     0     0     0     0

In [68]:
new_cols = 'col1 col2 col3 col4 col5 col6 col7'.split()
df4 = df3.reindex(columns=new_cols, fill_value=0)
df4

col1  col2  col3  col4  col5  col6  col7
A    86    65    63    55     5    15     0
B    82    16    44    16    86    19     0
C    13     7    56    49    79    43     0
D    83    51    58    58    60    32     0
E    93     9    27    82    18    51     0
F    93    67    72    55    62    86     0
G     0     0     0     0     0     0     0
H     0     0     0     0     0     0     0
K     0     0     0     0     0     0     0

In [74]:
df5 = df2.reindex(index=new_idx, columns=new_cols, fill_value=0)
df5

col1  col2  col3  col4  col5  col6  col7
A    86    65    63    55     5    15     0
B    82    16    44    16    86    19     0
C    13     7    56    49    79    43     0
D    83    51    58    58    60    32     0
E    93     9    27    82    18    51     0
F    93    67    72    55    62    86     0
G     0     0     0     0     0     0     0
H     0     0     0     0     0     0     0
K     0     0     0     0     0     0     0

col1  col2  col3  col4  col5  col6  col7
A  86.0  65.0  63.0  55.0   5.0  15.0   NaN
B  82.0  16.0  44.0  16.0  86.0  19.0   NaN
C  13.0   7.0  56.0  49.0  79.0  43.0   NaN
D  83.0  51.0  58.0  58.0  60.0  32.0   NaN
E  93.0   9.0  27.0  82.0  18.0  51.0   NaN
F  93.0  67.0  72.0  55.0  62.0  86.0   NaN
G   NaN   NaN   NaN   NaN   NaN   NaN   NaN
H   NaN   NaN   NaN   NaN   NaN   NaN   NaN
K   NaN   NaN   NaN   NaN   NaN   NaN   NaN

BMI calculator

In [1]:
name1 = 'Hong'
height_m1 = 1.6
weight_kg1 = 46

name2 = 'YK'
height_m2 = 2
weight_kg2 = 90

In [2]:
def bmi_calculator(name, height_m, weight_kg):
    bmi = weight_kg / (height_m ** 2)
    print('bmi: ')
    print(bmi)
    if bmi < 25:
        return name + ' not overweight'
    else:
        return name + ' overweight'

In [5]:
result1 = bmi_calculator(name1, height_m1, weight_kg1)
print(result1)
result2 = bmi_calculator(name2, height_m2, weight_kg2)
print(result2)

bmi: 
17.968749999999996
Hong not overweight
bmi: 
22.5
YK not overweight
